import Typograf from 'typograf';

export const TYPOGRAPHY_SKIP_TAGS = new Set([
  'code',
  'kbd',
  'math',
  'object',
  'pre',
  'samp',
  'script',
  'style',
  'textarea',
  'var'
]);

export const TYPOGRAPHY_WRAPPER_CLASSES = new Set(['nowrap-date-range']);

const BRAND_PART_RULE = 'ru/nbsp/shelkovoPartName';

if (!Typograf.getRule(BRAND_PART_RULE)) {
  Typograf.addRule({
    name: BRAND_PART_RULE,
    // Keep brand compounds like "Шелково Ривер" on one line.
    handler: (text) => text.replace(/Шелково (?=[A-ZА-ЯЁ])/gu, 'Шелково\u00A0')
  });
}

const BEFORE_NUMBER_SIGN_RULE = 'ru/nbsp/beforeNumberSign';

if (!Typograf.getRule(BEFORE_NUMBER_SIGN_RULE)) {
  Typograf.addRule({
    name: BEFORE_NUMBER_SIGN_RULE,
    // Run before ru/nbsp/afterNumberSign inserts its narrow non-breaking space.
    index: 505,
    handler: (text) => text.replace(/(?<=[\p{L}.,;:!?)])\s+(?=№\s*\d)/gu, '\u00A0')
  });
}

const DATE_RANGE = new RegExp(
  `(?<![\\p{L}\\p{N}_])([12]\\d|3[01]|0?[1-9])[-–]([12]\\d|3[01]|0?[1-9])[ \\u00A0](${Typograf.getData('ru/monthGenCase')})(?![\\p{L}\\p{N}_])`,
  'gu'
);
const DATE_RANGE_DASH_RULE = 'ru/dash/shelkovoDateRange';
const DATE_RANGE_HTML_RULE = 'ru/html/nowrapDateRange';

if (!Typograf.getRule(DATE_RANGE_DASH_RULE)) {
  Typograf.addRule({
    name: DATE_RANGE_DASH_RULE,
    // daysMonth (310) only recognizes a range after whitespace, missing quotes
    // and hidden HTML tags. Normalize those boundaries in every output mode.
    index: 315,
    handler: (text) => text.replace(DATE_RANGE, '$1–$2\u00A0$3')
  });
}

if (!Typograf.getRule(DATE_RANGE_HTML_RULE)) {
  Typograf.addRule({
    name: DATE_RANGE_HTML_RULE,
    // The html group (1210) runs after spaces and dashes.
    htmlAttrs: false,
    handler: (text) => text.replace(DATE_RANGE, '<span class="nowrap-date-range">$&</span>')
  });
  Typograf.addRule({
    name: 'ru/html/unwrapDateRange',
    queue: 'hide-safe-tags-html',
    htmlAttrs: false,
    // Unwrap after protected elements and comments, before ordinary HTML tags.
    handler: (text) => text.replace(/<span class="nowrap-date-range">([^<]*)<\/span>/gu, '$1')
  });
}

const typograf = new Typograf({
  locale: ['ru', 'en-US'],
  processingSeparateParts: true,
  // Keep the author's link boundaries, matching node-local AST processing.
  disableRule: 'common/punctuation/quoteLink'
});

for (const tag of TYPOGRAPHY_SKIP_TAGS) {
  typograf.addSafeTag(new RegExp(`<${tag}(?:\\s[^>]*)?>[\\s\\S]*?<\\/${tag}>`, 'gi'));
}

// Typograf does not decode &amp;, but its punctuation rules can split the
// semicolon from an escaped literal entity. Keep the entire spelling intact.
typograf.addSafeTag(/&amp;(?:#(?:x[\da-f]+|\d+);|[a-z][a-z\d]*;)?/gi);
// Numeric spellings of markup characters must stay text in prepared HTML too.
typograf.addSafeTag(/&#(?:0*(?:38|60|62)|x0*(?:26|3c|3e));/gi);
// Typograf's ordinary tag matcher stops at the first >, even in an attribute.
// Shield complete start tags with quoted markup before cleanup or text rules.
typograf.addSafeTag(
  /<[a-z][\w:-]*\s(?:[^"'<>]|"[^"]*"|'[^']*')*(?:"[^"]*[<>][^"]*"|'[^']*[<>][^']*')(?:[^"'<>]|"[^"]*"|'[^']*')*>/gi
);

const escapeText = (text: string): string =>
  text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');

/** Literal text → text, including attributes, textContent, and diff inputs. */
export const formatText = (text: string): string =>
  typograf
    .execute(escapeText(text), {
      ruleFilter: (rule) => rule.group !== 'html' && rule.htmlAttrs !== false
    })
    .replace(/&(?:lt|gt|amp);/gu, (entity) =>
      entity === '&lt;' ? '<' : entity === '&gt;' ? '>' : '&'
    );

/** Literal text → HTML containing only markup generated by typography rules. */
export const formatTextHtml = (text: string): string => typograf.execute(escapeText(text));

/** Prepared HTML → HTML. The caller owns the safety of the supplied markup. */
export const formatDynamicHtml = (html: string): string => typograf.execute(html);
